server:
  port: 9092
spring:
  application:
    name: websocket-template
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_tutorial?serverTimezone=Asia/Shanghai
    username: root
    password: admin123
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-init-sql: select 1
  redis:
    lettuce:
      pool:
        max-idle: 8
        min-idle: 2
    port: 6379
    password: admin123
    host: 192.168.30.131
mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
