---
--- 数据类型
--- Generated by Luanalysis
--- Created by songshiping.
--- DateTime: 2023/9/6 21:46
---

print(type("Hello world"))   --> string
print(type(10.4*3))       --> number
print(type(print))       --> function
print(type(type))        --> function
print(type(true))        --> boolean
print(type(nil))        --> nil
print(type(type(X)))      --> string
