---
--- 函数
--- Generated by Luanalysis
--- Created by songshiping.
--- DateTime: 2023/9/6 22:31
---

--[[
optional_function_scope: 该参数是可选的指定函数是全局函数还是局部函数，未设置该参数默认为全局函数，如果你需要设置函数为局部函数需要使用关键字 local。
function_name: 指定函数名称。
argument1, argument2, argument3..., argumentn: 函数参数，多个参数以逗号隔开，函数也可以不带参数。
function_body: 函数体，函数中需要执行的代码语句块。
result_params_comma_separated: 函数返回值，Lua语言函数可以返回多个值，每个值以逗号隔开。
--]]
function reverse(a, b, c)
    return c, b, a
end

print(reverse('songshiping', 'zhangsan', 'lisi'))

