---
--- 流程语句
--- Generated by Luanalysis
--- Created by songshiping.
--- DateTime: 2023/9/6 22:28
---
function doScore(score)
    if score > 90 then
        return '优秀'
    elseif score > 80 then
        return '中等'
    else
        return 'normal'
    end
end

print(doScore(99))
print(doScore(10))
print(doScore(85))
