---
--- lua变量
--- Generated by Luanalysis
--- Created by songshiping.
--- DateTime: 2023/9/6 21:55
---

a = 5 -- 全局变量

local b = 5 -- 局部变量

function test()
    c = 5 -- 全局变量
    local d = 6 -- 局部变量
end

test()
print('---01', c, d)

do
    local a = 6
    b = 6
    print('---02', a, b)
end

print('---03', a, b)

-- 赋值语句
a = 'hello' .. 'world'
n = 3
print(a, n)


-- Lua 可以对多个变量同时赋值，变量列表和值列表的各个元素用逗号分开，赋值语句右边的值会依次赋给左边的变量。
m, k = 10, 2 * n
print(m, k)

-- 遇到赋值语句Lua会先计算右边所有的值然后再执行赋值操作，所以我们可以这样进行交换变量的值：
g, q = 1, 2
print('swap before ', g, q)
g, q = q, g

print('swap after ', g, q)

--[[
a. 变量个数 > 值的个数             按变量个数补足nil
b. 变量个数 < 值的个数             多余的值会被忽略
--]]
m, v, c = 1, 2
print(m, v, c)

m, v = 2, 4, 5
print(m, v)


--[[
t[i]
t.i                 -- 当索引为字符串类型时的一种简化写法
gettable_event(t,i) -- 采用索引访问本质上是一个类似这样的函数调用
--]]
site = {}
site['baidu'] = 'https://www.baidu.com'
print(site.baidu, site['baidu'])

