server:
  port: 9090
spring:
  application:
    name: security-dynamic-role
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_tutorial?serverTimezone=Asia/Shanghai
    username: root
    password: admin123
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-init-sql: select 1
  security:
    user:
      name: admin
      password: lzvrzone
# 自定义配置项
application:
  # 安全配置
  security:
    # 允许的ip和端口
    allowed-origin:
      - localhost:8080
      - localhost:9090
    # 允许通过的请求头
    allowed-header: '*'
    # 允许通过的请求方式
    allowed-method:
      - GET
      - POST
      - DELETE
      - PUT
    # 允许跨域访问的路径
    allowed-path: /**
    # 配置忽略路径
    ant-matchers:
      - /auth/**
      - /websocket/**
mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
