server:
  port: 9090
spring:
  application:
    name: security-dynamic-role
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_tutorial?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-init-sql: select 1
  security:
    user:
      name: admin
      password: lzvrzone
mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
