spring:
  redis:
    lettuce:
      pool:
        max-idle: 8
        min-idle: 2
        max-wait: -1
        # 连接池最大阻塞等待时间(使用负值表示没有限制)
        max-active: 1000
    port: 6379
    password: lzvrzone
    host: localhost

server:
  port: 9099
