spring:
  application:
    name: redis-template
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_tutorial?serverTimezone=Asia/Shanghai
    username: root
    password: admin123
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-init-sql: select 1
  redis:
    lettuce:
      pool:
        max-active: 8
        min-idle: 2
    host: localhost
    password: lzvrzone
server:
  port: 9093
mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl